language: node_js
node_js:
- '4'
- '6'
- '7'
cache:
  yarn: true
  directories:
  - node_modules
script:
- npm test
sudo: false
deploy:
  provider: npm
  email: jordan.schroter@gmail.com
  api_key:
    secure: IWG3bjpgi1pLgDcxk1qtcdKseWjLISetvK7SvyPUfbbKY6Lge8pCWYmB0Bp6Ye7xwaw0yHraPf0YQlHD8sEb7UkGaOKTfDmxf2oc/MoAf7mpkt1oHJOQM8gC3wO3CkujUV4DjON1dAvM8eo06imWTVkE9gUtXkGZdj5uAdEBNswlcEUQ/B9t/rq/i7ifmdMVZMFDrmg24QCwXoqfnhw2xYh6KS3kvGL95fBBQPWmDqskUBYYCgeiH29j6rQhbEfN2LA6Eds2w13uZMK4PQkdH01Ff8qPFUzmO+GKIPXUNgSvXJlR+fU/rODf2nYFGhK5q0fZXTR3hycvaJZcia7XsbLGyAbKgVdbKqLG3ox0K62PoQluwsSYcxNRUV4jOb3U/bJlcVds6mGtavpFXr2CxaTOmsYkxASkKiAGYBQAtECUqd1nTlhwMJJgPeL2D6qFwG8hTskLza+znAmxJL2vLQiV4OYkeuTzE703LsfWQA/eHMkMlos0SJZP7Q+QTyNuNr4txcR4TqRYuGmrTSlg4DVzrIl7m+bbegANXSRzALo1TFGQWXCuUbNDMC+ph7h9fTi6I0x2YWaj/FA15Y6tYoxFpfLiQbsAqq/6J+EIKZE/mQRk9s7BRlthjfQf/3tnYDQ8dF0Zs7R6qNgk9eGyVilRDL5u6FWlXDb90eMV9x4=
  on:
    tags: true
    repo: jschr/lambda-response
    branch: master