language: node_js
node_js:
- '4'
- '6'
- '7'
cache:
  yarn: true
  directories:
  - node_modules
script:
- npm test
sudo: false
deploy:
  provider: npm
  email: jordan.schroter@gmail.com
  api_key:
    secure: zpNRtLiigqyI2LEO1dFOsus/BAHhvY9Q1ZwiiVrqsy/OSPgEs2a17x8wxgJM81mqCtH/+sREGkZOzChr38sG9djz01wr6M+6LDmjqd4lLYrMOm/a4cqGG2GZhy5nSF6PYLLGAyh4+Ci8HiCTGqEJwB1LXx7M5T+PfRxWqqPy022PDzjLy56wvUVLDV3grMdtfLL5ZEVOMc1OZ5oOWvmtkDmQDBm+vK+DhlgR2CV+nUPvO5jYBL/H3ROnu9C5DCgPpoD6+yOtClzKkLO9bbW0E+OnkavTYbwX+mIJMHSmFQyMSs2LWOXnoCQcvV66Jlahx1I8ISIKWWvS90JDRASL9APUD2CBmvFZ8REiPT6LI/Q+Mbc3E7yJBAhbWOeuWW5HYwTnxry6WjwYOYLfcvKrRqB82pekwBzzGbEqwgr6fFptwjGskdHXK3WS2s+DvFsGj5FQQtL3KVJhE8P0flo9b8jZTYCYIJObbS23PvTH78UP5nIXvjFbs9jGhugDGHZOjjXfLICz8/m7eMjbAtqwWp+WWinMujblEcyh2XhrNqB3yiL2tdvIuCGvarBig8zbkjN8SRlZtd11Ht59Z5mQaRbXpmas7ToZ+hBBS6qaTkLUYTwtnChV3dJwvLuieBRytRSVZZ6VJAWuvyKnzjScli/wuD3zFSbh1Pfz2PZWpeE=
  on:
    tags: true
    repo: jschr/lambda-response
    branch: master
